import "@/styles/globals.css";

import { Provider } from "./provider";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NavBar from "@/components/main/navbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Provider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NavBar />
          {children}
        </Provider>
      </body>
    </html>
  );
}
